#!/usr/bin/env node
"use strict";

// build-psl.js — one-time generator for chrome-extension/psl.js.
//
// Fetches publicsuffix.org/list/public_suffix_list.dat, parses it into
// the three rule categories (normal, wildcard `*.x`, exception `!x`),
// and emits a self-contained JS module that exports them as Sets.
//
// Vanilla Node, stdlib only. Run manually when we want to refresh:
//   node tools/build-psl.js
// Output is committed; the build script is NOT run at install time.
//
// Pin strategy: snapshot sha256 is recorded in the output header. A
// later run that produces a different sha is a drift signal — review
// the diff before committing.

const https = require("https");
const fs = require("fs");
const crypto = require("crypto");
const path = require("path");

const PSL_URL = "https://publicsuffix.org/list/public_suffix_list.dat";
const OUT_PATH = path.join(__dirname, "..", "chrome-extension", "psl.js");

function fetchUtf8(url) {
  return new Promise((resolve, reject) => {
    https
      .get(url, (res) => {
        if (res.statusCode !== 200) {
          reject(new Error("HTTP " + res.statusCode + " for " + url));
          return;
        }
        const chunks = [];
        res.on("data", (c) => chunks.push(c));
        res.on("end", () => resolve(Buffer.concat(chunks).toString("utf8")));
      })
      .on("error", reject);
  });
}

function parse(raw) {
  const normal = [];
  const wildcard = []; // stored without the leading "*."
  const exception = []; // stored without the leading "!"
  for (const lineRaw of raw.split("\n")) {
    const line = lineRaw.trim();
    if (!line) continue;
    if (line.startsWith("//")) continue;
    // PSL entries are space-or-comment-terminated; take first token.
    const tok = line.split(/\s+/)[0];
    if (!tok) continue;
    if (tok.startsWith("!")) {
      exception.push(tok.slice(1).toLowerCase());
    } else if (tok.startsWith("*.")) {
      wildcard.push(tok.slice(2).toLowerCase());
    } else {
      normal.push(tok.toLowerCase());
    }
  }
  return { normal, wildcard, exception };
}

function emit({ normal, wildcard, exception, sha256, fetchedAt }) {
  const fmt = (arr) =>
    arr
      .sort()
      .map((s) => "  " + JSON.stringify(s))
      .join(",\n");
  return `/*
 * psl.js — Public Suffix List, vendored for eTLD+1 third-party detection.
 *
 * Generated by tools/build-psl.js — DO NOT EDIT BY HAND.
 *
 * THIS FILE IS A DERIVATIVE WORK OF THE PUBLIC SUFFIX LIST.
 *
 * Source:   https://publicsuffix.org/list/public_suffix_list.dat
 * Fetched:  ${fetchedAt}
 * sha256:   ${sha256}
 * Rules:    ${normal.length} normal + ${wildcard.length} wildcard + ${exception.length} exception
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/.
 *
 * The MPL-2.0 license applies to this file only. The surrounding
 * wearecooked project is Apache-2.0; MPL-2.0 is per-file and does not
 * extend to consumer code that imports the exported Sets.
 *
 * Consumers (e.g. scoper.js) implement the Mozilla matching algorithm:
 *  1. Find longest matching rule (normal, wildcard expanded).
 *  2. If an exception rule matches, treat it as if the rule is one label
 *     shorter than the matched wildcard rule.
 *  3. The public suffix is the matched rule (with wildcard expanded);
 *     the eTLD+1 is the public suffix prefixed by one more label.
 */

const PSL_NORMAL = new Set([
${fmt(normal)}
]);

const PSL_WILDCARD = new Set([
${fmt(wildcard)}
]);

const PSL_EXCEPTION = new Set([
${fmt(exception)}
]);

// Service-worker-compatible global export (no ES module syntax).
self.PSL_NORMAL = PSL_NORMAL;
self.PSL_WILDCARD = PSL_WILDCARD;
self.PSL_EXCEPTION = PSL_EXCEPTION;
`;
}

(async () => {
  console.log("Fetching " + PSL_URL + " ...");
  const raw = await fetchUtf8(PSL_URL);
  const sha256 = crypto.createHash("sha256").update(raw).digest("hex");
  const parsed = parse(raw);
  const fetchedAt = new Date().toISOString().slice(0, 10);
  const out = emit({ ...parsed, sha256, fetchedAt });
  fs.writeFileSync(OUT_PATH, out);
  console.log(
    "Wrote " +
      OUT_PATH +
      "\n  rules: " +
      parsed.normal.length +
      " normal + " +
      parsed.wildcard.length +
      " wildcard + " +
      parsed.exception.length +
      " exception" +
      "\n  sha256: " +
      sha256,
  );
})();
